# Generated by Django 2.2.17 on 2021-06-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='invites_by_email_address',
            field=models.TextField(blank=True, help_text='Add comma separated emails e.g. example1@domain.com,example2@domain.com', verbose_name='Add guests by email address'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Published webinars are live and their email invitations are sent to all the added recipients.', verbose_name='Is Published'),
        ),
    ]
